"""initial migration

Revision ID: 80e73a51a626
Revises: 
Create Date: 2024-09-04 11:20:19.684287

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e73a51a626'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
